// Database procedure for gitclient — in-memory tables populated from git output.
//
// Unlike socialfeed, there is NO persistence. The database is a read-only cache
// of git state, cleared and repopulated on each gc_refresh_all().
//
// Serves the History tab: branches, commits, history files, tags, stash, remotes, worktrees.

#include "gitclient.h"
#include <platform/platform.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Use generated field metadata from gitclient.orion.
// branches_fields[], commits_fields[], files_fields[], diff_fields[]
// are defined in the generated header.
//
// The gc_database_schema and gc_database_api symbols are aliased via #define
// in gitclient.h to match the gitclient_* prefix generated by orionc.

static const db_field_schema_t branches_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "name", DB_TYPE_STRING, 256, false, NULL, NULL },
  { "hash", DB_TYPE_STRING, 41, false, NULL, NULL },
  { "is_current", DB_TYPE_BOOL, 0, false, NULL, NULL },
  { "is_remote", DB_TYPE_BOOL, 0, false, NULL, NULL },
  { "activity", DB_TYPE_STRING, 32, false, NULL, NULL },
  { "kind", DB_TYPE_STRING, 16, false, NULL, NULL },
};

static const db_field_schema_t commits_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "branch_id", DB_TYPE_INT, 0, false, "branches", "id" },
  { "hash", DB_TYPE_STRING, 41, false, NULL, NULL },
  { "author", DB_TYPE_STRING, 64, false, NULL, NULL },
  { "date", DB_TYPE_STRING, 20, false, NULL, NULL },
  { "subject", DB_TYPE_STRING, 256, false, NULL, NULL },
};

static const db_field_schema_t files_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "commit_id", DB_TYPE_INT, 0, false, "commits", "id" },
  { "path", DB_TYPE_STRING, 512, false, NULL, NULL },
  { "status", DB_TYPE_STRING, 2, false, NULL, NULL },
  { "staged", DB_TYPE_BOOL, 0, false, NULL, NULL },
};

static const db_field_schema_t diff_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "content", DB_TYPE_STRING, 262144, false, NULL, NULL },
};

static const db_field_schema_t stash_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "ref", DB_TYPE_STRING, 64, false, NULL, NULL },
  { "message", DB_TYPE_STRING, 512, false, NULL, NULL },
  { "branch", DB_TYPE_STRING, 256, false, NULL, NULL },
};

static const db_field_schema_t remotes_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "name", DB_TYPE_STRING, 256, false, NULL, NULL },
  { "url", DB_TYPE_STRING, 512, false, NULL, NULL },
};

static const db_field_schema_t tags_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "name", DB_TYPE_STRING, 256, false, NULL, NULL },
  { "hash", DB_TYPE_STRING, 41, false, NULL, NULL },
  { "date", DB_TYPE_STRING, 20, false, NULL, NULL },
};

static const db_field_schema_t worktrees_schema_fields[] = {
  { "id", DB_TYPE_INT, 0, true, NULL, NULL },
  { "name", DB_TYPE_STRING, 256, false, NULL, NULL },
  { "path", DB_TYPE_STRING, 512, false, NULL, NULL },
  { "branch", DB_TYPE_STRING, 96, false, NULL, NULL },
  { "status", DB_TYPE_STRING, 16, false, NULL, NULL },
  { "is_current", DB_TYPE_BOOL, 0, false, NULL, NULL },
  { "is_linked", DB_TYPE_BOOL, 0, false, NULL, NULL },
  { "is_detached", DB_TYPE_BOOL, 0, false, NULL, NULL },
  { "is_prunable", DB_TYPE_BOOL, 0, false, NULL, NULL },
};

static db_table_schema_t gc_database_tables[] = {
  { TABLE_BRANCHES, "branches", NULL, branches_schema_fields, 7, NULL, 0 },
  { TABLE_COMMITS,  "commits",  NULL, commits_schema_fields,  6, NULL, 0 },
  { TABLE_FILES,    "files",    NULL, files_schema_fields,    5, NULL, 0 },
  { TABLE_DIFF,     "diff",     NULL, diff_schema_fields,     2, NULL, 0 },
  { TABLE_TAGS,     "tags",     NULL, tags_schema_fields,     4, NULL, 0 },
  { TABLE_STASH,    "stash",    NULL, stash_schema_fields,    4, NULL, 0 },
  { TABLE_REMOTES,  "remotes",  NULL, remotes_schema_fields,  3, NULL, 0 },
  { TABLE_WORKTREES, "worktrees", NULL, worktrees_schema_fields, 9, NULL, 0 },
};

static db_schema_def_t gitclient_database_schema = {
  .name = NULL,
  .class_name = NULL,
  .source_path = NULL,
  .tables = gc_database_tables,
  .table_count = TABLE_COUNT,
};

static result_t field_text_from_meta(const void *object,
                                     const db_field_meta_t *fields,
                                     int field_count, int first_column,
                                     uint32_t msg, uint32_t wparam,
                                     void *lparam) {
  if (msg != dbObjGetFieldText || !object || !fields || !lparam)
    return false;

  int field_index = (int)LOWORD(wparam) - first_column;
  size_t buf_sz = (size_t)HIWORD(wparam);
  if (field_index < 0 || field_index >= field_count || buf_sz == 0)
    return false;

  const db_field_meta_t *field = &fields[field_index];
  const void *value = (const char *)object + field->offset;
  char *buf = (char *)lparam;
  switch (field->type) {
    case DB_TYPE_INT:
      snprintf(buf, buf_sz, "%d", *(const int *)value);
      return true;
    case DB_TYPE_STRING:
      snprintf(buf, buf_sz, "%s", (const char *)value);
      return true;
    case DB_TYPE_BOOL:
      snprintf(buf, buf_sz, "%d", *(const bool *)value ? 1 : 0);
      return true;
    case DB_TYPE_FLOAT:
      snprintf(buf, buf_sz, "%g", *(const float *)value);
      return true;
    case DB_TYPE_DOUBLE:
      snprintf(buf, buf_sz, "%g", *(const double *)value);
      return true;
  }
  return false;
}

#define GC_OBJECT_PROC(name, fields, first_column)                              \
  static result_t name(const void *object, uint32_t msg, uint32_t wparam,       \
                       void *lparam) {                                           \
    return field_text_from_meta(object, fields, ARRAY_LEN(fields), first_column,\
                                msg, wparam, lparam);                            \
  }

static result_t file_object_proc(const void *object, uint32_t msg,
                                 uint32_t wparam, void *lparam) {
  if (msg != dbObjGetFieldText || !object || !lparam)
    return false;
  const db_file_t *f = (const db_file_t *)object;
  int field_index = (int)LOWORD(wparam) - GC_COL_FILE_ID;
  size_t buf_sz = (size_t)HIWORD(wparam);
  char *buf = (char *)lparam;
  if (field_index < 0 || field_index >= 5 || buf_sz == 0) return false;
  switch (field_index) {
    case 0: snprintf(buf, buf_sz, "%d", f->id);            return true;
    case 1: snprintf(buf, buf_sz, "%d", f->commit_id);     return true;
    case 2: snprintf(buf, buf_sz, "%s", f->path);           return true;
    case 3: snprintf(buf, buf_sz, "%s", gc_status_label(f->status[0])); return true;
    case 4: snprintf(buf, buf_sz, "%d", f->staged ? 1 : 0);  return true;
  }
  return false;
}

GC_OBJECT_PROC(branch_object_proc, branches_fields, GC_COL_BRANCH_ID)
GC_OBJECT_PROC(commit_object_proc, commits_fields, GC_COL_COMMIT_ID)
GC_OBJECT_PROC(diff_object_proc, diff_fields, GC_COL_DIFF_ID)
GC_OBJECT_PROC(tag_object_proc, tags_fields, GC_COL_TAG_ID)
GC_OBJECT_PROC(stash_object_proc, stash_fields, GC_COL_STASH_ID)
GC_OBJECT_PROC(remote_object_proc, remotes_fields, GC_COL_REMOTE_ID)
GC_OBJECT_PROC(worktree_object_proc, worktrees_fields, GC_COL_WORKTREE_ID)

static const db_field_msg_binding_t branch_field_bindings[] = {
  { "id", GC_COL_BRANCH_ID }, { "name", GC_COL_BRANCH_NAME },
  { "hash", GC_COL_BRANCH_HASH },
  { "is_current", GC_COL_BRANCH_IS_CURRENT },
  { "is_remote", GC_COL_BRANCH_IS_REMOTE },
  { "activity", GC_COL_BRANCH_ACTIVITY },
  { "kind", GC_COL_BRANCH_KIND },
};
static const db_field_msg_binding_t commit_field_bindings[] = {
  { "id", GC_COL_COMMIT_ID }, { "branch_id", GC_COL_COMMIT_BRANCH_ID },
  { "hash", GC_COL_COMMIT_HASH },
  { "author", GC_COL_COMMIT_AUTHOR }, { "date", GC_COL_COMMIT_DATE },
  { "subject", GC_COL_COMMIT_SUBJECT },
};
static const db_field_msg_binding_t file_field_bindings[] = {
  { "id", GC_COL_FILE_ID }, { "commit_id", GC_COL_FILE_COMMIT_ID },
  { "path", GC_COL_FILE_PATH },
  { "status", GC_COL_FILE_STATUS }, { "staged", GC_COL_FILE_STAGED },
};
static const db_field_msg_binding_t diff_field_bindings[] = {
  { "id", GC_COL_DIFF_ID }, { "content", GC_COL_DIFF_CONTENT },
};
static const db_field_msg_binding_t tag_field_bindings[] = {
  { "id", GC_COL_TAG_ID }, { "name", GC_COL_TAG_NAME },
  { "hash", GC_COL_TAG_HASH }, { "date", GC_COL_TAG_DATE },
};
static const db_field_msg_binding_t stash_field_bindings[] = {
  { "id", GC_COL_STASH_ID }, { "ref", GC_COL_STASH_REF },
  { "message", GC_COL_STASH_MESSAGE }, { "branch", GC_COL_STASH_BRANCH },
};
static const db_field_msg_binding_t remote_field_bindings[] = {
  { "id", GC_COL_REMOTE_ID }, { "name", GC_COL_REMOTE_NAME },
  { "url", GC_COL_REMOTE_URL },
};
static const db_field_msg_binding_t worktree_field_bindings[] = {
  { "id", GC_COL_WORKTREE_ID }, { "name", GC_COL_WORKTREE_NAME },
  { "path", GC_COL_WORKTREE_PATH }, { "branch", GC_COL_WORKTREE_BRANCH },
  { "status", GC_COL_WORKTREE_STATUS }, { "is_current", GC_COL_WORKTREE_IS_CURRENT },
  { "is_linked", GC_COL_WORKTREE_IS_LINKED }, { "is_detached", GC_COL_WORKTREE_IS_DETACHED },
  { "is_prunable", GC_COL_WORKTREE_IS_PRUNABLE },
};

// ═══════════════════════════════════════════════════════════════════════════
// Internal context
// ═══════════════════════════════════════════════════════════════════════════

typedef struct {
  git_repo_t *repo;

  db_branche_t *branches;
  int branch_count;
  int branch_capacity;
  int next_branch_id;

  db_commit_t *commits;
  int commit_count;
  int commit_capacity;
  int next_commit_id;

  db_file_t *files;
  int file_count;
  int file_capacity;
  int next_file_id;

  db_diff_t *diff;
  int diff_count;
  int diff_capacity;
  int next_diff_id;

  db_tag_t *tags;
  int tag_count;
  int tag_capacity;
  int next_tag_id;

  db_stash_t *stash;
  int stash_count;
  int stash_capacity;
  int next_stash_id;

  db_remote_t *remotes;
  int remote_count;
  int remote_capacity;
  int next_remote_id;

  db_worktree_t worktrees[GC_MAX_WORKTREES];
  int worktree_count;
} gc_db_context_t;

// ═══════════════════════════════════════════════════════════════════════════
// Array helpers
// ═══════════════════════════════════════════════════════════════════════════

static void ensure_capacity(void **rows, int *capacity, int count,
                            size_t row_size, int initial) {
  if (count < *capacity) return;
  int next = (*capacity == 0) ? initial : (*capacity * 2);
  *rows = realloc(*rows, (size_t)next * row_size);
  *capacity = next;
}

static void *append_row(void **rows, int *count, int *capacity,
                        size_t row_size, int *next_id, int initial) {
  ensure_capacity(rows, capacity, *count, row_size, initial);
  char *row = (char *)(*rows) + ((size_t)(*count) * row_size);
  memset(row, 0, row_size);
  (*count)++;
  *(int *)row = (*next_id)++;
  return row;
}

static void clear_table(void **rows, int *count, int *capacity, int *next_id) {
  free(*rows);
  *rows = NULL;
  *count = 0;
  *capacity = 0;
  *next_id = 1;
}

static void *find_by_id(void *rows, int count, size_t row_size, int id) {
  char *base = (char *)rows;
  for (int i = 0; i < count; i++) {
    char *row = base + ((size_t)i * row_size);
    if (*(int *)row == id) return row;
  }
  return NULL;
}

static void *find_branch_by_name(gc_db_context_t *ctx, const char *name) {
  for (int i = 0; i < ctx->branch_count; i++) {
    if (strcmp(ctx->branches[i].name, name) == 0)
      return &ctx->branches[i];
  }
  return NULL;
}

static lresult_t fetch_all(void *rows, int count, size_t row_size) {
  result_node_t *head = NULL, *tail = NULL;
  for (int i = 0; i < count; i++) {
    char *row = (char *)rows + ((size_t)i * row_size);
    result_node_t *node = malloc(sizeof(result_node_t) + sizeof(void *));
    node->next = NULL;
    *(void **)node->data = row;
    if (tail) tail->next = node;
    else head = node;
    tail = node;
  }
  return (lresult_t)head;
}

static lresult_t fetch_filtered_bool(void *rows, int count, size_t row_size,
                                     size_t filter_offset, bool filter_value) {
  result_node_t *head = NULL, *tail = NULL;
  for (int i = 0; i < count; i++) {
    char *row = (char *)rows + ((size_t)i * row_size);
    if (*(bool *)(row + filter_offset) != filter_value) continue;
    result_node_t *node = malloc(sizeof(result_node_t) + sizeof(void *));
    node->next = NULL;
    *(void **)node->data = row;
    if (tail) tail->next = node;
    else head = node;
    tail = node;
  }
  return (lresult_t)head;
}

static lresult_t fetch_filtered_int(void *rows, int count, size_t row_size,
                                    size_t filter_offset, int filter_value) {
  result_node_t *head = NULL, *tail = NULL;
  for (int i = 0; i < count; i++) {
    char *row = (char *)rows + ((size_t)i * row_size);
    if (*(int *)(row + filter_offset) != filter_value) continue;
    result_node_t *node = malloc(sizeof(result_node_t) + sizeof(void *));
    node->next = NULL;
    *(void **)node->data = row;
    if (tail) tail->next = node; else head = node;
    tail = node;
  }
  return (lresult_t)head;
}

// ═══════════════════════════════════════════════════════════════════════════
// Database procedure
// ═══════════════════════════════════════════════════════════════════════════

lresult_t gitclient_db(database_t *db, uint32_t msg, uint32_t wparam, void *lparam) {
  gc_db_context_t *ctx = (gc_db_context_t *)db->userdata;

  switch (msg) {
    case dbCreate: {
      ctx = calloc(1, sizeof(gc_db_context_t));
      if (!ctx) return 0;
      ctx->next_branch_id = 1;
      ctx->next_commit_id = 1;
      ctx->next_file_id   = 1;
      ctx->next_diff_id   = 1;
      ctx->next_tag_id    = 1;
      ctx->next_remote_id = 1;
      ctx->next_stash_id  = 1;
      db->userdata = ctx;
      return 1;
    }

    case dbDestroy: {
      if (!ctx) return 0;
      free(ctx->branches);
      free(ctx->commits);
      free(ctx->files);
      free(ctx->diff);
      free(ctx->tags);
      free(ctx->remotes);
      free(ctx->stash);
      free(ctx);
      db->userdata = NULL;
      return 1;
    }

    case dbLoad: {
      if (!ctx) return 0;
      git_repo_t *repo = (git_repo_t *)lparam;
      if (!repo) return 0;
      ctx->repo = repo;

      clear_table((void **)&ctx->branches, &ctx->branch_count, &ctx->branch_capacity, &ctx->next_branch_id);
      clear_table((void **)&ctx->commits,  &ctx->commit_count,  &ctx->commit_capacity,  &ctx->next_commit_id);
      clear_table((void **)&ctx->files,    &ctx->file_count,    &ctx->file_capacity,    &ctx->next_file_id);
      clear_table((void **)&ctx->diff,     &ctx->diff_count,    &ctx->diff_capacity,    &ctx->next_diff_id);
      clear_table((void **)&ctx->tags,     &ctx->tag_count,     &ctx->tag_capacity,     &ctx->next_tag_id);
      clear_table((void **)&ctx->stash,    &ctx->stash_count,   &ctx->stash_capacity,   &ctx->next_stash_id);
      clear_table((void **)&ctx->remotes,  &ctx->remote_count,  &ctx->remote_capacity,  &ctx->next_remote_id);
      memset(ctx->worktrees, 0, sizeof(ctx->worktrees));
      ctx->worktree_count = 0;

      // Branches
      int branch_count = 0;
      git_branch_t raw_branches[256];
      int branch_ids[256] = {0};
      {
        int count = git_get_branches(repo, raw_branches, 256);
        branch_count = count;
        for (int i = 0; i < count; i++) {
          db_branche_t *rec = append_row((void **)&ctx->branches, &ctx->branch_count,
                                         &ctx->branch_capacity, sizeof(db_branche_t),
                                         &ctx->next_branch_id, 32);
          strncpy(rec->name, raw_branches[i].name, sizeof(rec->name) - 1);
          strncpy(rec->hash, raw_branches[i].hash, sizeof(rec->hash) - 1);
          strncpy(rec->activity, raw_branches[i].activity, sizeof(rec->activity) - 1);
          strncpy(rec->kind, raw_branches[i].kind, sizeof(rec->kind) - 1);
          rec->is_current = raw_branches[i].is_current;
          rec->is_remote  = raw_branches[i].is_remote;
          branch_ids[i] = rec->id;
        }
      }

      // Commits — only load the current branch's log eagerly.
      // Other branches lazy-load when the user selects them.
      {
        for (int b = 0; b < branch_count; b++) {
          if (!raw_branches[b].is_current) continue;
          git_commit_t raw[500];
          int count = git_get_log_ref(repo, raw_branches[b].name, raw, 500);
          for (int i = 0; i < count; i++) {
            db_commit_t *rec = append_row((void **)&ctx->commits, &ctx->commit_count,
                                          &ctx->commit_capacity, sizeof(db_commit_t),
                                          &ctx->next_commit_id, 256);
            rec->branch_id = branch_ids[b];
            strncpy(rec->hash,    raw[i].hash,    sizeof(rec->hash) - 1);
            strncpy(rec->author,  raw[i].author,  sizeof(rec->author) - 1);
            strncpy(rec->date,    raw[i].date,    sizeof(rec->date) - 1);
            strncpy(rec->subject, raw[i].subject, sizeof(rec->subject) - 1);
          }
          break;
        }
      }

      // Working-tree files are handled by the separate changes_db;
      // this database only serves the History tab (commit_id > 0).

      // Tags
      {
        git_tag_t raw[256];
        int count = git_get_tags(repo, raw, 256);
        for (int i = 0; i < count; i++) {
          db_tag_t *rec = append_row((void **)&ctx->tags, &ctx->tag_count,
                                     &ctx->tag_capacity, sizeof(db_tag_t),
                                     &ctx->next_tag_id, 32);
          strncpy(rec->name, raw[i].name, sizeof(rec->name) - 1);
          strncpy(rec->hash, raw[i].hash, sizeof(rec->hash) - 1);
          strncpy(rec->date, raw[i].date, sizeof(rec->date) - 1);
        }
      }

      // Stash
      {
        git_stash_t raw[64];
        int count = git_get_stash(repo, raw, 64);
        for (int i = 0; i < count; i++) {
          db_stash_t *rec = append_row((void **)&ctx->stash, &ctx->stash_count,
                                       &ctx->stash_capacity, sizeof(db_stash_t),
                                       &ctx->next_stash_id, 16);
          strncpy(rec->ref,     raw[i].ref,     sizeof(rec->ref) - 1);
          strncpy(rec->message, raw[i].message, sizeof(rec->message) - 1);
          strncpy(rec->branch,  raw[i].branch,  sizeof(rec->branch) - 1);
        }
      }

      // Remotes
      {
        char raw[16][256];
        int count = git_get_remotes(repo, raw, 16);
        for (int i = 0; i < count; i++) {
          db_remote_t *rec = append_row((void **)&ctx->remotes, &ctx->remote_count,
                                        &ctx->remote_capacity, sizeof(db_remote_t),
                                        &ctx->next_remote_id, 8);
          strncpy(rec->name, raw[i], sizeof(rec->name) - 1);
          char url[512] = {0};
          if (git_get_remote_url(repo, raw[i], url, sizeof(url)))
            strncpy(rec->url, url, sizeof(rec->url) - 1);
        }
      }

      git_worktree_t raw_worktrees[GC_MAX_WORKTREES];
      int worktree_count = git_worktree_list(git_repo_path(repo), raw_worktrees, ARRAY_LEN(raw_worktrees));
      char current_path[512];
      if (!git_path_absolute(git_repo_path(repo), current_path, sizeof(current_path)))
        snprintf(current_path, sizeof(current_path), "%s", git_repo_path(repo));
      for (int i = 0; i < worktree_count; i++) {
        const git_worktree_t *raw = &raw_worktrees[i];
        if (raw->bare) continue;
        db_worktree_t *rec = &ctx->worktrees[ctx->worktree_count++];
        rec->id = ctx->worktree_count;
        git_worktree_label(raw, rec->name, sizeof(rec->name));
        if (!git_path_absolute(raw->path, rec->path, sizeof(rec->path)))
          snprintf(rec->path, sizeof(rec->path), "%s", raw->path);
        snprintf(rec->branch, sizeof(rec->branch), "%s", raw->branch);
        rec->is_current = !strcmp(rec->path, current_path);
        rec->is_linked = raw->linked; rec->is_detached = raw->detached; rec->is_prunable = raw->prunable;
        snprintf(rec->status, sizeof(rec->status), "%s", rec->is_current ? "Current" : rec->is_prunable ? "Prunable" :
                 rec->is_detached ? "Detached" : rec->is_linked ? "Linked" : "Main");
      }
      return 1;
    }

    case dbSave:
      return 1;

    case dbInsert: {
      if (!ctx) return (lresult_t)NULL;
      int table_id = wparam;
      const void *data = lparam;

      if (table_id == ID_DB_BRANCHES) {
        db_branche_t *rec = append_row((void **)&ctx->branches, &ctx->branch_count,
                                       &ctx->branch_capacity, sizeof(db_branche_t),
                                       &ctx->next_branch_id, 32);
        memcpy(rec, data, sizeof(db_branche_t));
        rec->id = ctx->next_branch_id - 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_COMMITS) {
        db_commit_t *rec = append_row((void **)&ctx->commits, &ctx->commit_count,
                                      &ctx->commit_capacity, sizeof(db_commit_t),
                                      &ctx->next_commit_id, 256);
        memcpy(rec, data, sizeof(db_commit_t));
        rec->id = ctx->next_commit_id - 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_FILES) {
        db_file_t *rec = append_row((void **)&ctx->files, &ctx->file_count,
                                    &ctx->file_capacity, sizeof(db_file_t),
                                    &ctx->next_file_id, 64);
        memcpy(rec, data, sizeof(db_file_t));
        rec->id = ctx->next_file_id - 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_DIFF) {
        if (ctx->diff_count == 0) {
          ensure_capacity((void **)&ctx->diff, &ctx->diff_capacity, 0,
                          sizeof(db_diff_t), 1);
          ctx->diff_count = 1;
        }
        db_diff_t *rec = &ctx->diff[0];
        memcpy(rec, data, sizeof(db_diff_t));
        rec->id = 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_TAGS) {
        db_tag_t *rec = append_row((void **)&ctx->tags, &ctx->tag_count,
                                    &ctx->tag_capacity, sizeof(db_tag_t),
                                    &ctx->next_tag_id, 32);
        memcpy(rec, data, sizeof(db_tag_t));
        rec->id = ctx->next_tag_id - 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_STASH) {
        db_stash_t *rec = append_row((void **)&ctx->stash, &ctx->stash_count,
                                      &ctx->stash_capacity, sizeof(db_stash_t),
                                      &ctx->next_stash_id, 16);
        memcpy(rec, data, sizeof(db_stash_t));
        rec->id = ctx->next_stash_id - 1;
        return (lresult_t)rec;
      }
      if (table_id == ID_DB_REMOTES) {
        db_remote_t *rec = append_row((void **)&ctx->remotes, &ctx->remote_count,
                                      &ctx->remote_capacity, sizeof(db_remote_t),
                                      &ctx->next_remote_id, 8);
        memcpy(rec, data, sizeof(db_remote_t));
        rec->id = ctx->next_remote_id - 1;
        return (lresult_t)rec;
      }
      return (lresult_t)NULL;
    }

    case dbUpdate:
      db->dirty = true;
      return 1;

    case dbDelete: {
      if (!ctx) return 0;
      int table_id = wparam;

      if ((intptr_t)lparam == 0) {
        if (table_id == ID_DB_BRANCHES) {
          clear_table((void **)&ctx->branches, &ctx->branch_count,
                      &ctx->branch_capacity, &ctx->next_branch_id);
          return 1;
        }
        if (table_id == ID_DB_COMMITS) {
          clear_table((void **)&ctx->commits, &ctx->commit_count,
                      &ctx->commit_capacity, &ctx->next_commit_id);
          return 1;
        }
        if (table_id == ID_DB_FILES) {
          clear_table((void **)&ctx->files, &ctx->file_count,
                      &ctx->file_capacity, &ctx->next_file_id);
          return 1;
        }
        if (table_id == ID_DB_DIFF) {
          clear_table((void **)&ctx->diff, &ctx->diff_count,
                      &ctx->diff_capacity, &ctx->next_diff_id);
          return 1;
        }
        if (table_id == ID_DB_TAGS) {
          clear_table((void **)&ctx->tags, &ctx->tag_count,
                      &ctx->tag_capacity, &ctx->next_tag_id);
          return 1;
        }
        if (table_id == ID_DB_STASH) {
          clear_table((void **)&ctx->stash, &ctx->stash_count,
                      &ctx->stash_capacity, &ctx->next_stash_id);
          return 1;
        }
        if (table_id == ID_DB_REMOTES) {
          clear_table((void **)&ctx->remotes, &ctx->remote_count,
                      &ctx->remote_capacity, &ctx->next_remote_id);
          return 1;
        }
        if (table_id == ID_DB_WORKTREES) {
          memset(ctx->worktrees, 0, sizeof(ctx->worktrees));
          ctx->worktree_count = 0;
          return 1;
        }
      }
      return 0;
    }

    case dbFetch: {
      if (!ctx) return (lresult_t)NULL;
      int table_id = LOWORD(wparam);
      int filter_field = HIWORD(wparam);
      int filter_value = (int)(intptr_t)lparam;

      GC_LOG("dbFetch: table=%d filter_field=%d filter_value=%d counts=[%d,%d,%d,%d]",
             table_id, filter_field, filter_value, ctx->branch_count,
             ctx->commit_count, ctx->file_count, ctx->diff_count);

      if (table_id == ID_DB_BRANCHES) {
        if (filter_field == ID_DB_BRANCHES_IS_REMOTE)
          return fetch_filtered_bool(ctx->branches, ctx->branch_count,
                                     sizeof(db_branche_t),
                                     offsetof(db_branche_t, is_remote),
                                     (bool)filter_value);
        return fetch_all(ctx->branches, ctx->branch_count, sizeof(db_branche_t));
      }
      if (table_id == ID_DB_COMMITS) {
        if (filter_field == ID_DB_COMMITS_BRANCH_ID) {
          bool loaded = false;
          for (int i = 0; i < ctx->commit_count; i++) {
            if (ctx->commits[i].branch_id == filter_value) { loaded = true; break; }
          }
          if (!loaded && ctx->repo) {
            db_branche_t *br = (db_branche_t *)find_by_id(ctx->branches,
                               ctx->branch_count, sizeof(db_branche_t), filter_value);
            if (br && br->name[0]) {
              git_commit_t raw[500];
              int count = git_get_log_ref(ctx->repo, br->name, raw, 500);
              for (int i = 0; i < count; i++) {
                db_commit_t *rec = append_row((void **)&ctx->commits, &ctx->commit_count,
                                              &ctx->commit_capacity, sizeof(db_commit_t),
                                              &ctx->next_commit_id, 256);
                rec->branch_id = filter_value;
                strncpy(rec->hash,    raw[i].hash,    sizeof(rec->hash) - 1);
                strncpy(rec->author,  raw[i].author,  sizeof(rec->author) - 1);
                strncpy(rec->date,    raw[i].date,    sizeof(rec->date) - 1);
                strncpy(rec->subject, raw[i].subject, sizeof(rec->subject) - 1);
              }
            }
          }
          return fetch_filtered_int(ctx->commits, ctx->commit_count,
                                    sizeof(db_commit_t),
                                    offsetof(db_commit_t, branch_id), filter_value);
        }
        return fetch_all(ctx->commits, ctx->commit_count, sizeof(db_commit_t));
      }
      if (table_id == ID_DB_FILES) {
        if (filter_field == ID_DB_FILES_COMMIT_ID) {
          // History DB only has commit-associated files (commit_id > 0).
          // Lazy-load: if no files cached for this commit yet, fetch from git.
          bool cached = false;
          for (int i = 0; i < ctx->file_count; i++) {
            if (ctx->files[i].commit_id == filter_value) { cached = true; break; }
          }
          if (!cached && ctx->repo) {
            db_commit_t *c = (db_commit_t *)find_by_id(ctx->commits,
                               ctx->commit_count, sizeof(db_commit_t), filter_value);
            if (c && c->hash[0]) {
              char buf[64 * 1024] = {0};
              const char *args[] = {
                "git", "show", "--name-only", "--pretty=format:", c->hash, NULL
              };
              if (git_run_sync(ctx->repo, args, buf, sizeof(buf))) {
                char *line = buf;
                while (*line) {
                  char *nl = strchr(line, '\n');
                  if (nl) *nl = '\0';
                  if (line[0] && strcmp(line, c->hash) != 0) {
                    db_file_t *rec = append_row((void **)&ctx->files, &ctx->file_count,
                                                &ctx->file_capacity, sizeof(db_file_t),
                                                &ctx->next_file_id, 64);
                    rec->commit_id = filter_value;
                    rec->status[0] = 'M';
                    rec->status[1] = '\0';
                    rec->staged    = false;
                    strncpy(rec->path, line, sizeof(rec->path) - 1);
                  }
                  if (!nl) break;
                  line = nl + 1;
                }
              }
            }
          }
          return fetch_filtered_int(ctx->files, ctx->file_count,
                                    sizeof(db_file_t),
                                    offsetof(db_file_t, commit_id), filter_value);
        }
        return fetch_all(ctx->files, ctx->file_count, sizeof(db_file_t));
      }
      if (table_id == ID_DB_DIFF)
        return fetch_all(ctx->diff, ctx->diff_count, sizeof(db_diff_t));
      if (table_id == ID_DB_TAGS)
        return fetch_all(ctx->tags, ctx->tag_count, sizeof(db_tag_t));
      if (table_id == ID_DB_STASH)
        return fetch_all(ctx->stash, ctx->stash_count, sizeof(db_stash_t));
      if (table_id == ID_DB_REMOTES)
        return fetch_all(ctx->remotes, ctx->remote_count, sizeof(db_remote_t));
      if (table_id == ID_DB_WORKTREES)
        return fetch_all(ctx->worktrees, ctx->worktree_count, sizeof(db_worktree_t));
      return (lresult_t)NULL;
    }

    case dbFind: {
      if (!ctx) return (lresult_t)NULL;
      int table_id = LOWORD(wparam);
      int search_field = HIWORD(wparam);
      uintptr_t value = (uintptr_t)lparam;

      if (table_id == ID_DB_BRANCHES) {
        if (search_field == 0 || search_field == ID_DB_BRANCHES_ID)
          return (lresult_t)find_by_id(ctx->branches, ctx->branch_count,
                                        sizeof(db_branche_t), (int)value);
        if (search_field == ID_DB_BRANCHES_NAME)
          return (lresult_t)find_branch_by_name(ctx, (const char *)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_COMMITS) {
        if (search_field == 0 || search_field == ID_DB_COMMITS_ID)
          return (lresult_t)find_by_id(ctx->commits, ctx->commit_count,
                                        sizeof(db_commit_t), (int)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_FILES) {
        if (search_field == 0 || search_field == ID_DB_FILES_ID)
          return (lresult_t)find_by_id(ctx->files, ctx->file_count,
                                        sizeof(db_file_t), (int)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_DIFF) {
        if (ctx->diff_count > 0) return (lresult_t)&ctx->diff[0];
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_TAGS) {
        if (search_field == 0 || search_field == ID_DB_TAGS_ID)
          return (lresult_t)find_by_id(ctx->tags, ctx->tag_count,
                                        sizeof(db_tag_t), (int)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_STASH) {
        if (search_field == 0 || search_field == ID_DB_STASH_ID)
          return (lresult_t)find_by_id(ctx->stash, ctx->stash_count,
                                        sizeof(db_stash_t), (int)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_REMOTES) {
        if (search_field == 0 || search_field == ID_DB_REMOTES_ID)
          return (lresult_t)find_by_id(ctx->remotes, ctx->remote_count,
                                        sizeof(db_remote_t), (int)value);
        return (lresult_t)NULL;
      }
      if (table_id == ID_DB_WORKTREES) {
        if (search_field == ID_DB_WORKTREES_ID)
          return (lresult_t)find_by_id(ctx->worktrees, ctx->worktree_count, sizeof(db_worktree_t), (int)value);
        if (search_field == ID_DB_WORKTREES_PATH)
          for (int i = 0; i < ctx->worktree_count; i++)
            if (value && !strcmp(ctx->worktrees[i].path, (const char *)value)) return (lresult_t)&ctx->worktrees[i];
        return (lresult_t)NULL;
      }
      return (lresult_t)NULL;
    }

    case dbGetDirty:
      return 0;

    case dbGetObjectProc:
      switch ((int)wparam) {
        case ID_DB_BRANCHES: return (lresult_t)branch_object_proc;
        case ID_DB_COMMITS:  return (lresult_t)commit_object_proc;
        case ID_DB_FILES:    return (lresult_t)file_object_proc;
        case ID_DB_DIFF:     return (lresult_t)diff_object_proc;
        case ID_DB_TAGS:     return (lresult_t)tag_object_proc;
        case ID_DB_STASH:    return (lresult_t)stash_object_proc;
        case ID_DB_REMOTES:  return (lresult_t)remote_object_proc;
        case ID_DB_WORKTREES: return (lresult_t)worktree_object_proc;
        default:             return (lresult_t)NULL;
      }

    case dbGetFieldBindings: {
      int *count_out = (int *)lparam;
      switch ((int)wparam) {
        case ID_DB_BRANCHES:
          if (count_out) *count_out = ARRAY_LEN(branch_field_bindings);
          return (lresult_t)branch_field_bindings;
        case ID_DB_COMMITS:
          if (count_out) *count_out = ARRAY_LEN(commit_field_bindings);
          return (lresult_t)commit_field_bindings;
        case ID_DB_FILES:
          if (count_out) *count_out = ARRAY_LEN(file_field_bindings);
          return (lresult_t)file_field_bindings;
        case ID_DB_DIFF:
          if (count_out) *count_out = ARRAY_LEN(diff_field_bindings);
          return (lresult_t)diff_field_bindings;
        case ID_DB_TAGS:
          if (count_out) *count_out = ARRAY_LEN(tag_field_bindings);
          return (lresult_t)tag_field_bindings;
        case ID_DB_STASH:
          if (count_out) *count_out = ARRAY_LEN(stash_field_bindings);
          return (lresult_t)stash_field_bindings;
        case ID_DB_REMOTES:
          if (count_out) *count_out = ARRAY_LEN(remote_field_bindings);
          return (lresult_t)remote_field_bindings;
        case ID_DB_WORKTREES:
          if (count_out) *count_out = ARRAY_LEN(worktree_field_bindings);
          return (lresult_t)worktree_field_bindings;
        default:
          if (count_out) *count_out = 0;
          return (lresult_t)NULL;
      }
    }

    case dbGetSchema:
      gc_database_schema.name = db->name;
      gc_database_schema.class_name = db->class_name;
      gc_database_schema.source_path = db->source_path;
      return (lresult_t)&gc_database_schema;

    case dbGetFieldMeta: {
      int *count_out = (int *)lparam;
      switch (wparam) {
        case ID_DB_BRANCHES:
          if (count_out) *count_out = ARRAY_LEN(branches_fields);
          return (lresult_t)branches_fields;
        case ID_DB_COMMITS:
          if (count_out) *count_out = ARRAY_LEN(commits_fields);
          return (lresult_t)commits_fields;
        case ID_DB_FILES:
          if (count_out) *count_out = ARRAY_LEN(files_fields);
          return (lresult_t)files_fields;
        case ID_DB_DIFF:
          if (count_out) *count_out = ARRAY_LEN(diff_fields);
          return (lresult_t)diff_fields;
        case ID_DB_TAGS:
          if (count_out) *count_out = ARRAY_LEN(tags_fields);
          return (lresult_t)tags_fields;
        case ID_DB_STASH:
          if (count_out) *count_out = ARRAY_LEN(stash_fields);
          return (lresult_t)stash_fields;
        case ID_DB_REMOTES:
          if (count_out) *count_out = ARRAY_LEN(remotes_fields);
          return (lresult_t)remotes_fields;
        case ID_DB_WORKTREES:
          if (count_out) *count_out = ARRAY_LEN(worktrees_fields);
          return (lresult_t)worktrees_fields;
        default:
          if (count_out) *count_out = 0;
          return (lresult_t)NULL;
      }
    }

    case dbGetApi:
      return (lresult_t)&gc_database_api;
  }

  return 0;
}
