#ifndef __VGA_FONT_H__
#define __VGA_FONT_H__

// VGA-style monospace font renderer.
//
// Loads a 128x256 RGBA PNG character sheet (16 columns x 16 rows, each
// cell 8x16 pixels, white glyphs on transparent background) and exposes a
// simple API for rendering fixed-width text with independent foreground and
// background colours.
//
// The sheet is generated by tools/gen_vga_font and installed at
// <exe_dir>/../share/orion/vga-rom-font-8x16.png by the build system.
//
// Colours follow the framework's 0xAARRGGBB convention (same as
// get_sys_color / fill_rect / draw_text_small).

#include <stdbool.h>
#include <stdint.h>

// Physical dimensions of one character cell in screen pixels.
// These values control on-screen character size; increase them (for example
// to 128x128) to render larger glyphs while preserving font texture detail.
#define VGA_CHAR_W   8
#define VGA_CHAR_H   16

// Initialise the VGA font renderer by loading the sheet from sheet_path.
// Must be called after ui_init_graphics().
// Returns true on success, false if the file is missing or the GL texture
// cannot be created.  When false, all draw calls become no-ops.
bool vga_font_init(const char *sheet_path);

// Release the GL texture.  Safe to call even when init failed.
void vga_font_shutdown(void);

// Returns true when the font sheet was successfully loaded.
bool vga_font_loaded(void);

// Returns the renderer texture ID for the loaded VGA sheet, or 0 if not loaded.
uint32_t vga_font_texture_id(void);

// Draw a single character cell at screen position (x, y).
// fg / bg are 0xAARRGGBB; bg is drawn as a solid filled rectangle.
void vga_draw_char(int ch, int x, int y, uint32_t fg, uint32_t bg);

// Draw a NUL-terminated string on a single line at (x, y).
// Interprets only printable ASCII; other bytes are drawn as a solid block.
// Returns the total pixel width rendered (= strlen(text) * VGA_CHAR_W).
int vga_draw_text(const char *text, int x, int y, uint32_t fg, uint32_t bg);

// Draw at most max_chars characters from text, honouring the same rules as
// vga_draw_text.
int vga_draw_textn(const char *text, int max_chars,
                   int x, int y, uint32_t fg, uint32_t bg);

// Pixel width of a string (= strlen * VGA_CHAR_W, independent of content).
int vga_text_width(int char_count);

#endif /* __VGA_FONT_H__ */
