// gen_toolbox_atlas.c - pack downloaded Tabler PNGs into FormEditor toolbox.png.

#include <ctype.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_IMAGE_IMPLEMENTATION
#include "../user/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../user/stb_image_write.h"

typedef struct {
  char enum_name[96];
  char icon_name[96];
} icon_def_t;

static void usage(const char *argv0) {
  fprintf(stderr,
          "usage: %s manifest.txt icon-dir out.png out.h\n",
          argv0);
}

static char *trim(char *s) {
  while (*s && isspace((unsigned char)*s)) s++;
  char *e = s + strlen(s);
  while (e > s && isspace((unsigned char)e[-1])) *--e = '\0';
  return s;
}

static bool valid_enum_name(const char *s) {
  if (!s || !*s) return false;
  for (; *s; s++) {
    if (!isalnum((unsigned char)*s) && *s != '_')
      return false;
  }
  return true;
}

static bool duplicate_enum_name(const icon_def_t *defs, int count, const char *name) {
  for (int i = 0; i < count; i++) {
    if (strcmp(defs[i].enum_name, name) == 0)
      return true;
  }
  return false;
}

static bool read_manifest(const char *path, icon_def_t **out_defs, int *out_count) {
  FILE *f = fopen(path, "rb");
  if (!f) return false;

  int cap = 256;
  int count = 0;
  icon_def_t *defs = calloc((size_t)cap, sizeof(icon_def_t));
  if (!defs) {
    fclose(f);
    return false;
  }

  char line[512];
  while (fgets(line, sizeof(line), f)) {
    char *s = trim(line);
    if (!*s || *s == '#') continue;
    char *name = strtok(s, " \t");
    char *icon = strtok(NULL, " \t");
    if (!name || !icon) {
      free(defs);
      fclose(f);
      return false;
    }
    if (!valid_enum_name(name) || strcmp(name, "count") == 0 ||
        strcmp(name, "default") == 0 ||
        duplicate_enum_name(defs, count, name)) {
      fprintf(stderr, "gen_toolbox_atlas: invalid enum name '%s'\n", name);
      free(defs);
      fclose(f);
      return false;
    }
    if (count >= cap) {
      cap *= 2;
      icon_def_t *tmp = realloc(defs, (size_t)cap * sizeof(icon_def_t));
      if (!tmp) {
        free(defs);
        fclose(f);
        return false;
      }
      defs = tmp;
    }
    snprintf(defs[count].enum_name, sizeof(defs[count].enum_name), "%s", name);
    snprintf(defs[count].icon_name, sizeof(defs[count].icon_name), "%s", icon);
    count++;
  }

  fclose(f);
  *out_defs = defs;
  *out_count = count;
  return true;
}

static void downsample_icon(uint8_t *dst, int tile,
                            const uint8_t *src, int sw, int sh) {
  for (int y = 0; y < tile; y++) {
    int sy0 = (y * sh) / tile;
    int sy1 = ((y + 1) * sh) / tile;
    if (sy1 <= sy0) sy1 = sy0 + 1;
    for (int x = 0; x < tile; x++) {
      int sx0 = (x * sw) / tile;
      int sx1 = ((x + 1) * sw) / tile;
      if (sx1 <= sx0) sx1 = sx0 + 1;

      uint64_t aa = 0;
      int count = 0;
      for (int sy = sy0; sy < sy1 && sy < sh; sy++) {
        for (int sx = sx0; sx < sx1 && sx < sw; sx++) {
          const uint8_t *p = src + ((size_t)sy * sw + sx) * 4;
          aa += p[3];
          count++;
        }
      }

      uint8_t *d = dst + ((size_t)y * tile + x) * 4;
      d[0] = 255;
      d[1] = 255;
      d[2] = 255;
      d[3] = count > 0 ? (uint8_t)((aa + (uint64_t)count / 2) / (uint64_t)count) : 0;
    }
  }
}

static bool write_header(const char *path, const icon_def_t *defs, int count) {
  FILE *f = fopen(path, "wb");
  if (!f) return false;
  fprintf(f, "// Generated by tools/update_toolbox_atlas.sh. Do not edit by hand.\n");
  fprintf(f, "#ifndef __TOOLBOX_ICONS_H__\n");
  fprintf(f, "#define __TOOLBOX_ICONS_H__\n\n");
  fprintf(f, "typedef enum toolbox_icon_e {\n");
  for (int i = 0; i < count; i++)
    fprintf(f, "  toolbox_icon_%s = %d,\n", defs[i].enum_name, i);
  fprintf(f, "  toolbox_icon_count = %d,\n", count);
  fprintf(f, "  toolbox_icon_default = toolbox_icon_component,\n");
  fprintf(f, "} toolbox_icon_t;\n\n");
  fprintf(f, "#endif\n");
  fclose(f);
  return true;
}

int main(int argc, char **argv) {
  enum { TILE = 16, COLS = 16 };
  if (argc != 5) {
    usage(argv[0]);
    return 2;
  }

  icon_def_t *defs = NULL;
  int count = 0;
  if (!read_manifest(argv[1], &defs, &count) || count <= 0) {
    fprintf(stderr, "gen_toolbox_atlas: failed to read manifest\n");
    return 1;
  }

  int rows = (count + COLS - 1) / COLS;
  int w = COLS * TILE;
  int h = rows * TILE;
  uint8_t *atlas = calloc((size_t)w * h * 4, 1);
  uint8_t *icon = malloc((size_t)TILE * TILE * 4);
  if (!atlas || !icon) {
    free(defs);
    free(atlas);
    free(icon);
    return 1;
  }

  for (int i = 0; i < count; i++) {
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s.png", argv[2], defs[i].icon_name);
    int sw = 0, sh = 0, sc = 0;
    uint8_t *src = stbi_load(path, &sw, &sh, &sc, 4);
    if (!src) {
      fprintf(stderr, "gen_toolbox_atlas: missing icon %s\n", path);
      free(defs);
      free(atlas);
      free(icon);
      return 1;
    }
    downsample_icon(icon, TILE, src, sw, sh);
    stbi_image_free(src);

    int dx = (i % COLS) * TILE;
    int dy = (i / COLS) * TILE;
    for (int y = 0; y < TILE; y++) {
      memcpy(atlas + ((size_t)(dy + y) * w + dx) * 4,
             icon + (size_t)y * TILE * 4,
             (size_t)TILE * 4);
    }
  }

  bool ok = stbi_write_png(argv[3], w, h, 4, atlas, w * 4) != 0 &&
            write_header(argv[4], defs, count);
  free(defs);
  free(atlas);
  free(icon);
  return ok ? 0 : 1;
}
