// Generated by tools/build_button_atlas.py; edit transport.json.
#ifndef __TRANSPORT_ATLAS_H__
#define __TRANSPORT_ATLAS_H__

#define TRANSPORT_ATLAS_CELL_SIZE 128
#define TRANSPORT_ATLAS_COLUMNS   8
#define TRANSPORT_ATLAS_STATES    5

#endif
